###############################################################################
#                                                                         #
# THIS TEST GENERATES GAMMA RAYS 4CM FROM THE CENTRE OF THE TARGET 
# WHICH IS THE ORIGIN. Seeing Resolution
#  
################################################################################

#/p26/analysis/dirname 
/p26/analysis/filename Stable-Test

/p26/phys/SelectPhysics LowEnergy_EM


#/p26/det/setGeThickDetectorThickness 1. cm
#/p26/det/setGeThinDetectorMate Vacuum
/p26/det/UseGeThickDetector true
/p26/det/UseGeThinDetector true


### use the cylindrical NaI Scintillator?
/p26/det/UseNaICylinder false



#### FUTURE FEATURES ####
### use the LaBr crystal?
#/p26/det/UseLaBrDetector false
### use the cubic NaI Scintillator?
#/p26/det/UseNaICube false



### which gamma detector should we use?
/p26/det/UseSega true
/p26/det/UseClover false



/run/initialize
#/run/setCutForRegion Target 10 cm
#/run/setCutForRegion GeThickDetector 0.010 mm
#/run/setCutForRegion GeThinDetector 0.010 mm


### UNCOMMENT TO CREATE A HEPREP FILE
### BUT ONLY DO A FEW EVENTS!

#/vis/scene/create
#/vis/open HepRepFile
#/vis/drawVolume
#/vis/viewer/flush
#/vis/scene/add/trajectories
#/vis/scene/add/hits




### what output do you want?
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/grdm/verbose 0


### don't mess with this
#/grdm/noVolumes
#/grdm/selectVolume Detector
/grdm/allVolumes



#######################################
###         SOURCE INFO             ###
### COMMENT OUT WHAT YOU DON'T WANT ###
#######################################

### For a monoenergetic beam ###
#/gps/particle e-
#/gps/energy 1000.0 keV
#/gps/position 0 0.0 0 cm

#/gps/pos/type Beam
#/gps/pos/shape Circle
#/gps/pos/radius 0.2 cm
#/gps/pos/sigma_r 0.06 cm

#/gps/ang/type beam1d
#/gps/ang/sigma_r 5.0 deg

#/gps/ene/type Mono
#/gps/ene/mono 1000.0 keV



### for trying a non-radially symmteric beam
#/gps/pos/shape/Ellipsoid
#/gps/pos/sigmax 8.582 cm
#/gps/pos/sigmay 2.018 cm
#/gps/ang/type beam1d

#/gps/ene/type Gauss
#/gps/ene/mono 400 MeV
#/gps/ene/sigma 50. MeV



### For beta decay ###
#/gps/source/intensity 1
#/gps/position 0 0 0
#/gps/ang/type iso
#/gps/ene/mono 0.0 MeV
#/gps/ion 17 31  ## This is the Z and A of the beta-decaying nucleus
#/grdm/fBeta 1


### For gamma decay ###
/gps/source/intensity 1
/gps/particle gamma
/gps/position 0 0 0 cm
/gps/ang/type iso
/gps/energy 1333 keV ## Change this if you want!

### odds and ends ###
#/gps/ang/type beam1D
#/gps/ene/type Mono
#/gps/ene/mono 2.0 MeV










############



# No daughter decays in analogue MC mode
#/grdm/analogueMC 1
#/grdm/nucleusLimits 90 90 28 28
/run/beamOn 1000
# No daughter decays in VR MC mode
#/grdm/analogueMC 0
#/grdm/BRbias 0
#/run/beamOn 10000


