###############################################################################
#                                                                         #
# THIS TEST GENERATES GAMMA RAYS 4CM FROM THE CENTRE OF THE TARGET 
# WHICH IS THE ORIGIN. Seeing Resolution
#  
################################################################################

/p26/analysis/dirname root_files/
/p26/analysis/filename All_SeGA_0

/p26/phys/SelectPhysics LowEnergy_EM_Livermore


#/p26/det/setGeThickDetectorThickness 1. cm
#/p26/det/setGeThinDetectorMate Vacuum
/p26/det/UseGeThickDetector false
/p26/det/UseGeThinDetector false
/p26/det/UseGeThickDetectorCryo false
/p26/det/UseGeThickDetectorCryoEndCap false


### use the LaBr crystal?
/p26/det/UseLaBrDetector false

### use the NaI Scintillator?
### NOTE:  Even though it says "Cylinder" here,
###         the NaI scintillator is likely to be square and is square here!

/p26/det/UseNaICylinder false


#### FUTURE FEATURES ####

### use the cubic NaI Scintillator?
#/p26/det/UseNaICube false


### which gamma detector should we use?
/p26/det/UseSega true
/p26/det/UseClover false


/run/initialize
#/run/setCutForRegion Target 10 cm
#/run/setCutForRegion GeThickDetector 0.010 mm
#/run/setCutForRegion GeThinDetector 0.010 mm


### UNCOMMENT TO CREATE A HEPREP FILE
### BUT ONLY DO A FEW EVENTS!

#/vis/scene/create
#/vis/open HepRepFile
#/vis/drawVolume
#/vis/viewer/flush
#/vis/scene/add/trajectories
#/vis/scene/add/hits


### what output do you want?
/run/verbose 0
/event/verbose 0
/tracking/verbose 2
/grdm/verbose 0

### don't mess with this
#/grdm/noVolumes
#/grdm/selectVolume Detector
/grdm/allVolumes

### Setting custom Decay Data
#/grdm/setRadioactiveDecayFile 16 28 DecayData/Decay_z16.a28
#/grdm/setPhotoEvaporationFile 15 28 DecayData/Gamma_z15.a28

#/grdm/setRadioactiveDecayFile 15 28 DecayData/Decay_z15.a28
#/grdm/setPhotoEvaporationFile 14 28 DecayData/Gamma_z14.a28

#/grdm/setRadioactiveDecayFile 14 26 DecayData/Decay_z14.a26
#/grdm/setPhotoEvaporationFile 13 26 DecayData/Gamma_z13.a26
#/grdm/setRadioactiveDecayFile 13 26 DecayData/Decay_z13.a26
#/grdm/setPhotoEvaporationFile 12 26 DecayData/Gamma_z12.a26

#######################################
###         SOURCE INFO             ###
### COMMENT OUT WHAT YOU DON'T WANT ###
#######################################

### For gamma decay ###
#######################                         All

/gps/source/intensity 0.75
/gps/ion 16 28
/gps/position 0 0 0 cm
/gps/ang/type iso
/gps/energy 0 keV

#/gps/source/intensity 0.25
#/gps/ion 14 26
#/gps/position 0 0 0 cm
#/gps/ang/type iso
#/gps/energy 0 keV

############

# No daughter decays in analogue MC mode
#/grdm/analogueMC 1
#/grdm/nucleusLimits 90 90 28 28
#/run/beamOn 15000000
/run/beamOn 1
#/run/beamOn 11
# No daughter decays in VR MC mode
#/grdm/analogueMC 0
#/grdm/BRbias 0
#/run/beamOn 10000
